# =========================================================
# QUIZCRAFT — users/management/commands/seed_data.py
# -----------------------------------------------------------
# WHY: the Adaptive Quiz Generator (users/views.py's
# generate_adaptive_quiz) needs a real question bank per subject
# and difficulty to actually be "adaptive" — with only a handful
# of demo questions, every attempt looks the same and there's
# nothing to adapt between. This file is pure DATA (no MongoDB
# calls here), kept separate from seed_questions.py so the command
# itself stays small and this list can be extended over time just
# by adding more tuples below.
#
# FORMAT: each entry is a tuple of
#   (subject, difficulty, question_text, option1, option2, option3, option4, correct_answer)
# `correct_answer` is copied EXACTLY from one of the four options
# (matching how add_question() stores answers already), which is
# checked in seed_questions.py to catch a typo before it ever
# reaches MongoDB.
#
# WHICH MODULE USES THIS: users/management/commands/seed_questions.py
# (run via `python manage.py seed_questions`).
# =========================================================

QUESTIONS = [

    # =====================================================
    # PYTHON - 50 questions
    # =====================================================
    ("Python", "easy", "What is the correct file extension for Python files?",
     ".pt", ".pyt", ".py", ".pyth", ".py"),
    ("Python", "easy", "Which keyword is used to define a function in Python?",
     "func", "def", "function", "lambda", "def"),
    ("Python", "easy", "Which symbol is used for a single-line comment in Python?",
     "//", "#", "<!-- -->", "/* */", "#"),
    ("Python", "easy", "Which of these is a mutable data type in Python?",
     "tuple", "string", "list", "int", "list"),
    ("Python", "easy", "What does the len() function do?",
     "Returns the largest element", "Returns the length of an object", "Returns the type", "Deletes an object", "Returns the length of an object"),
    ("Python", "easy", "Which data type is used to store True/False values?",
     "bool", "bit", "flag", "binary", "bool"),
    ("Python", "easy", "How do you start a block of code in Python?",
     "Curly braces", "Indentation", "Semicolon", "Parentheses", "Indentation"),
    ("Python", "easy", "Which operator is used for exponentiation in Python?",
     "^", "**", "exp()", "^^", "**"),
    ("Python", "easy", "What is the output of print(3 + 2 * 2)?",
     "10", "7", "9", "12", "7"),
    ("Python", "easy", "Which method adds an item to the end of a list?",
     "append()", "add()", "insert()", "extend()", "append()"),
    ("Python", "easy", "Which of the following is used to create a list in Python?",
     "{}", "()", "[]", "<>", "[]"),
    ("Python", "easy", "What is the correct way to import a module named math?",
     "include math", "import math", "using math", "require math", "import math"),
    ("Python", "easy", "Which function converts a string to an integer?",
     "int()", "str()", "float()", "num()", "int()"),
    ("Python", "easy", "What does the 'in' keyword check for in a list?",
     "Only index", "Membership", "Data type", "Length", "Membership"),
    ("Python", "easy", "Which keyword is used to exit a loop early in Python?",
     "exit", "stop", "break", "return", "break"),
    ("Python", "easy", "What is the output of type(5.0) in Python?",
     "<class 'int'>", "<class 'float'>", "<class 'double'>", "<class 'str'>", "<class 'float'>"),
    ("Python", "easy", "Which of these is the correct way to write a multi-line comment?",
     "// comment //", "# comment #", "''' comment '''", "<!-- comment -->", "''' comment '''"),
    ("Python", "medium", "Which keyword is used to create a function in Python that can be called with an unknown number of arguments?",
     "*args", "multi", "manyargs", "argslist", "*args"),
    ("Python", "medium", "What does the 'self' keyword refer to inside a class method?",
     "The class itself", "The current instance of the class", "A global variable", "The parent class", "The current instance of the class"),
    ("Python", "medium", "Which loop is guaranteed to run at least once in Python?",
     "for loop", "while loop", "Python has no such loop", "nested loop", "Python has no such loop"),
    ("Python", "medium", "What is the output of list(range(2, 10, 2))?",
     "[2, 4, 6, 8]", "[2, 4, 6, 8, 10]", "[2, 3, 4, 5, 6, 7, 8, 9]", "[0, 2, 4, 6, 8]", "[2, 4, 6, 8]"),
    ("Python", "medium", "Which data type stores key-value pairs?",
     "List", "Tuple", "Dictionary", "Set", "Dictionary"),
    ("Python", "medium", "What does the 'continue' statement do inside a loop?",
     "Stops the loop entirely", "Skips to the next iteration", "Restarts the program", "Does nothing", "Skips to the next iteration"),
    ("Python", "medium", "Which method removes and returns the last item of a list?",
     "remove()", "pop()", "del()", "discard()", "pop()"),
    ("Python", "medium", "What is a lambda function in Python?",
     "A named function", "An anonymous inline function", "A class method", "A loop construct", "An anonymous inline function"),
    ("Python", "medium", "What does the 'is' operator check?",
     "Value equality", "Identity (same object in memory)", "Data type only", "Length equality", "Identity (same object in memory)"),
    ("Python", "medium", "Which of the following creates a shallow copy of a list?",
     "list.copy()", "list.deepcopy()", "list.clone()", "list.dup()", "list.copy()"),
    ("Python", "medium", "What is the correct way to open a file for both reading and writing?",
     "open('file.txt','r')", "open('file.txt','w')", "open('file.txt','r+')", "open('file.txt','x')", "open('file.txt','r+')"),
    ("Python", "medium", "Which exception is raised when dividing by zero in Python?",
     "ValueError", "ZeroDivisionError", "ArithmeticError", "TypeError", "ZeroDivisionError"),
    ("Python", "medium", "What does the map() function do?",
     "Filters elements", "Applies a function to every item of an iterable", "Sorts a list", "Reduces a list to one value", "Applies a function to every item of an iterable"),
    ("Python", "medium", "Which keyword is used to handle exceptions in Python?",
     "catch", "except", "handle", "rescue", "except"),
    ("Python", "medium", "What is the output of bool(0)?",
     "True", "False", "0", "Error", "False"),
    ("Python", "medium", "Which built-in function returns an iterator of index-value pairs?",
     "zip()", "enumerate()", "index()", "pair()", "enumerate()"),
    ("Python", "medium", "What is the correct syntax for a ternary conditional expression in Python?",
     "a if condition else b", "if condition then a else b", "condition ? a : b", "a ? b : condition", "a if condition else b"),
    ("Python", "medium", "Which module is used to work with regular expressions in Python?",
     "regex", "re", "pyregex", "restring", "re"),
    ("Python", "medium", "What does the '__init__' method do in a Python class?",
     "Deletes an object", "Initializes a new object's attributes", "Imports a module", "Ends the program", "Initializes a new object's attributes"),
    ("Python", "medium", "Which statement correctly opens a file safely and closes it automatically?",
     "open('file.txt')", "with open('file.txt') as f:", "file.open('file.txt')", "read('file.txt')", "with open('file.txt') as f:"),
    ("Python", "hard", "What is the time complexity of a dictionary lookup on average?",
     "O(n)", "O(log n)", "O(1)", "O(n log n)", "O(1)"),
    ("Python", "hard", "What does the Global Interpreter Lock (GIL) primarily restrict?",
     "Memory allocation", "True parallel execution of Python bytecode across threads", "Disk I/O", "Network access", "True parallel execution of Python bytecode across threads"),
    ("Python", "hard", "What will list(enumerate(['a','b'])) return?",
     "[('a',0), ('b',1)]", "[(0,'a'), (1,'b')]", "['a','b']", "[0,1]", "[(0,'a'), (1,'b')]"),
    ("Python", "hard", "What does 'else' attached to a 'for' loop execute after?",
     "Never", "Only if the loop was broken early", "Only if the loop completed without break", "Always before the loop", "Only if the loop completed without break"),
    ("Python", "hard", "Which of these correctly describes a Python generator?",
     "A function that returns a list", "A function that uses 'yield' to produce values lazily", "A class decorator", "A built-in exception type", "A function that uses 'yield' to produce values lazily"),
    ("Python", "hard", "What is the output of the expression [x for x in range(5) if x % 2 == 0]?",
     "[0, 2, 4]", "[1, 3]", "[0, 1, 2, 3, 4]", "[2, 4]", "[0, 2, 4]"),
    ("Python", "hard", "What does the '@staticmethod' decorator do?",
     "Marks a method that receives no implicit first argument", "Marks a method that runs before __init__", "Creates a private variable", "Overrides a parent class method", "Marks a method that receives no implicit first argument"),
    ("Python", "hard", "Which of the following best describes Python's duck typing?",
     "Type checking happens at compile time", "An object's suitability is determined by its methods/behavior, not its class", "All variables must be explicitly typed", "Python does not support polymorphism", "An object's suitability is determined by its methods/behavior, not its class"),
    ("Python", "hard", "What is the output of print(0.1 + 0.2 == 0.3) in Python?",
     "True", "False", "Error", "None", "False"),
    ("Python", "hard", "Which method is used to create an iterator from an iterable object?",
     "iter()", "next()", "iterate()", "loop()", "iter()"),
    ("Python", "hard", "What is the primary difference between a list and a tuple?",
     "Tuples are mutable, lists are not", "Lists are mutable, tuples are not", "Both are immutable", "Both are mutable", "Lists are mutable, tuples are not"),
    ("Python", "hard", "What does functools.lru_cache primarily help with?",
     "Formatting strings", "Caching function results to speed up repeated calls", "Sorting lists", "Handling exceptions", "Caching function results to speed up repeated calls"),
    ("Python", "hard", "In Python, what is a decorator?",
     "A design pattern for UI styling", "A function that modifies the behavior of another function", "A built-in data type", "A type of loop", "A function that modifies the behavior of another function"),

    # =====================================================
    # JAVA - 50 questions
    # =====================================================
    ("Java", "easy", "Which keyword is used to create a class in Java?",
     "class", "struct", "define", "object", "class"),
    ("Java", "easy", "Which method is the entry point of a Java program?",
     "start()", "main()", "run()", "init()", "main()"),
    ("Java", "easy", "Which of these is a primitive data type in Java?",
     "String", "int", "Integer", "Object", "int"),
    ("Java", "easy", "Which symbol is used to end a statement in Java?",
     ":", ";", ".", ",", ";"),
    ("Java", "easy", "Which keyword is used to create an object in Java?",
     "new", "create", "make", "object", "new"),
    ("Java", "easy", "What is the default value of a boolean variable in Java?",
     "true", "false", "0", "null", "false"),
    ("Java", "easy", "Which of these is used for single-line comments in Java?",
     "#", "//", "<!-- -->", "**", "//"),
    ("Java", "easy", "Which package contains the Scanner class?",
     "java.io", "java.util", "java.lang", "java.net", "java.util"),
    ("Java", "easy", "Which operator is used to compare two values for equality?",
     "=", "==", "===", "eq", "=="),
    ("Java", "easy", "What does JVM stand for?",
     "Java Virtual Machine", "Java Verified Method", "Java Variable Manager", "Java Visual Model", "Java Virtual Machine"),
    ("Java", "easy", "Which keyword is used to inherit a class in Java?",
     "implements", "extends", "inherits", "super", "extends"),
    ("Java", "easy", "Which data type is used to store a single character in Java?",
     "String", "char", "Character", "text", "char"),
    ("Java", "easy", "Which loop checks the condition after executing the loop body at least once?",
     "for", "while", "do-while", "foreach", "do-while"),
    ("Java", "easy", "Which of these is NOT a Java access modifier?",
     "public", "private", "protected", "internal", "internal"),
    ("Java", "easy", "What is the size of an int in Java?",
     "16 bits", "32 bits", "64 bits", "8 bits", "32 bits"),
    ("Java", "easy", "Which keyword prevents a class from being inherited?",
     "static", "final", "private", "abstract", "final"),
    ("Java", "easy", "Which method converts a String to an integer?",
     "Integer.parseInt()", "String.toInt()", "int.parse()", "convert()", "Integer.parseInt()"),
    ("Java", "medium", "Which collection does not allow duplicate elements?",
     "ArrayList", "LinkedList", "HashSet", "Vector", "HashSet"),
    ("Java", "medium", "What is the purpose of the 'super' keyword in Java?",
     "Refers to the current object", "Refers to the parent class object/constructor", "Declares a static variable", "Creates a new thread", "Refers to the parent class object/constructor"),
    ("Java", "medium", "Which of these correctly describes method overloading?",
     "Same method name, different parameter list, same class", "Same method name and parameters in a subclass", "Overriding a private method", "Declaring a method as final", "Same method name, different parameter list, same class"),
    ("Java", "medium", "What is the purpose of an interface in Java?",
     "To create an object", "To define a contract of methods a class must implement", "To store static data only", "To replace a class entirely", "To define a contract of methods a class must implement"),
    ("Java", "medium", "Which keyword is used to handle exceptions in Java?",
     "except", "catch", "handle", "rescue", "catch"),
    ("Java", "medium", "What does the 'static' keyword mean for a class member?",
     "It belongs to each instance separately", "It belongs to the class rather than any instance", "It cannot be changed", "It is private by default", "It belongs to the class rather than any instance"),
    ("Java", "medium", "Which collection maintains insertion order and allows duplicates?",
     "HashSet", "TreeSet", "ArrayList", "HashMap", "ArrayList"),
    ("Java", "medium", "What is autoboxing in Java?",
     "Automatic conversion between primitive types and their wrapper classes", "Automatic memory deallocation", "Automatic exception handling", "Automatic type casting between classes", "Automatic conversion between primitive types and their wrapper classes"),
    ("Java", "medium", "Which keyword makes a variable's value constant?",
     "static", "final", "const", "readonly", "final"),
    ("Java", "medium", "What does the 'this' keyword refer to?",
     "The parent class", "The current object instance", "A static method", "An interface", "The current object instance"),
    ("Java", "medium", "Which block always executes whether or not an exception occurs?",
     "try", "catch", "finally", "throw", "finally"),
    ("Java", "medium", "What is the difference between '==' and '.equals()' for objects in Java?",
     "They behave identically", "'==' compares references, '.equals()' compares content (if overridden)", "'.equals()' always compares memory addresses", "'==' only works for primitives", "'==' compares references, '.equals()' compares content (if overridden)"),
    ("Java", "medium", "Which of these is used to create a thread in Java?",
     "Extending Thread class or implementing Runnable", "Using the 'async' keyword", "Using the 'fork' keyword", "Using the 'parallel' keyword", "Extending Thread class or implementing Runnable"),
    ("Java", "medium", "What is the purpose of a constructor in Java?",
     "To destroy an object", "To initialize a newly created object", "To define static methods only", "To import packages", "To initialize a newly created object"),
    ("Java", "medium", "Which of these is a checked exception in Java?",
     "NullPointerException", "ArithmeticException", "IOException", "ArrayIndexOutOfBoundsException", "IOException"),
    ("Java", "medium", "What does the 'abstract' keyword mean for a method?",
     "It has a full implementation", "It has no body and must be implemented by a subclass", "It cannot be overridden", "It runs only once", "It has no body and must be implemented by a subclass"),
    ("Java", "medium", "Which access modifier makes a member accessible only within its own class?",
     "public", "protected", "private", "default", "private"),
    ("Java", "medium", "What is the purpose of the 'ArrayList' class in Java?",
     "A fixed-size array", "A resizable array implementation of the List interface", "A key-value store", "A thread synchronization tool", "A resizable array implementation of the List interface"),
    ("Java", "hard", "What does the JVM's garbage collector reclaim?",
     "Unused variables", "Unreachable objects", "Compiled bytecode", "Static methods", "Unreachable objects"),
    ("Java", "hard", "Which of these best describes Java's 'final', 'finally', and 'finalize'?",
     "They all do the same thing", "'final' is a modifier, 'finally' is an exception block, 'finalize' is a garbage-collection hook method", "All three are keywords for loops", "They are all related to threads", "'final' is a modifier, 'finally' is an exception block, 'finalize' is a garbage-collection hook method"),
    ("Java", "hard", "What is the diamond problem in the context of Java interfaces?",
     "A syntax error in generics", "Ambiguity when a class inherits the same default method from two interfaces", "A memory leak pattern", "An issue with static imports", "Ambiguity when a class inherits the same default method from two interfaces"),
    ("Java", "hard", "Which of these correctly describes Java's String immutability?",
     "Strings can be changed in place after creation", "Once created, a String object's content cannot change; operations return new String objects", "Only String literals are immutable", "Immutability only applies to StringBuilder", "Once created, a String object's content cannot change; operations return new String objects"),
    ("Java", "hard", "What is the primary benefit of using generics in Java?",
     "Faster runtime execution", "Compile-time type safety without casting", "Automatic thread safety", "Reduced memory usage always", "Compile-time type safety without casting"),
    ("Java", "hard", "What does the 'volatile' keyword guarantee for a variable in a multithreaded context?",
     "Atomic compound operations", "Visibility of the latest value across threads", "Thread-safe collections", "Automatic synchronization of methods", "Visibility of the latest value across threads"),
    ("Java", "hard", "Which of these best describes a HashMap's average time complexity for get/put?",
     "O(n)", "O(log n)", "O(1) on average", "O(n log n)", "O(1) on average"),
    ("Java", "hard", "What is method overriding used for?",
     "Providing a different implementation of an inherited method in a subclass", "Declaring multiple methods with the same name in one class", "Making a method static", "Hiding a variable", "Providing a different implementation of an inherited method in a subclass"),
    ("Java", "hard", "What does the Java Memory Model primarily define?",
     "How the JVM compiles bytecode", "How threads interact through memory and what visibility guarantees exist", "How garbage collection algorithms are chosen", "How exceptions propagate", "How threads interact through memory and what visibility guarantees exist"),
    ("Java", "hard", "Which statement about Java's 'synchronized' keyword is correct?",
     "It only works on static methods", "It ensures only one thread can execute a block/method on a given lock at a time", "It prevents all exceptions", "It replaces the need for constructors", "It ensures only one thread can execute a block/method on a given lock at a time"),
    ("Java", "hard", "What is the purpose of the 'transient' keyword?",
     "Marks a field to be excluded from default serialization", "Marks a variable as thread-local", "Prevents inheritance", "Marks a method as deprecated", "Marks a field to be excluded from default serialization"),
    ("Java", "hard", "Which of these best describes Java's Stream API introduced in Java 8?",
     "A replacement for all collections", "A way to process sequences of elements with functional-style operations", "A networking library", "A database ORM", "A way to process sequences of elements with functional-style operations"),

    # =====================================================
    # C++ - 48 questions
    # =====================================================
    ("C++", "easy", "Which header file is required for input/output operations in C++?",
     "<stdio.h>", "<iostream>", "<conio.h>", "<iomanip>", "<iostream>"),
    ("C++", "easy", "Which symbol is used to end a statement in C++?",
     ":", ";", ".", ",", ";"),
    ("C++", "easy", "Which keyword is used to define a constant in C++?",
     "constant", "const", "final", "readonly", "const"),
    ("C++", "easy", "Which operator is used to access members of an object via a pointer?",
     ".", "->", "::", "&", "->"),
    ("C++", "easy", "Which of these is a valid way to declare an integer variable?",
     "int x;", "integer x;", "var x;", "x int;", "int x;"),
    ("C++", "easy", "Which function is the entry point of a C++ program?",
     "start()", "main()", "run()", "begin()", "main()"),
    ("C++", "easy", "Which operator is used for output in C++?",
     "<<", ">>", "->", "==", "<<"),
    ("C++", "easy", "Which keyword is used to create a class in C++?",
     "class", "struct only", "object", "define", "class"),
    ("C++", "easy", "What is the default access specifier for a class in C++?",
     "public", "private", "protected", "internal", "private"),
    ("C++", "easy", "Which operator is used for input in C++?",
     "<<", ">>", "->", "::", ">>"),
    ("C++", "easy", "Which of these correctly declares a pointer to an integer?",
     "int p;", "int *p;", "int &p;", "ptr int p;", "int *p;"),
    ("C++", "easy", "Which loop structure checks its condition before executing the body?",
     "do-while", "while", "for(;;)", "goto", "while"),
    ("C++", "easy", "Which keyword is used to include a header file?",
     "import", "include", "using", "require", "include"),
    ("C++", "easy", "What is the size of a char data type typically in C++?",
     "1 byte", "2 bytes", "4 bytes", "8 bytes", "1 byte"),
    ("C++", "easy", "Which operator is used to allocate dynamic memory in C++?",
     "malloc", "new", "alloc", "create", "new"),
    ("C++", "medium", "What happens when you delete a pointer twice in C++?",
     "Nothing, it is safe", "Compilation error", "Undefined behavior", "The pointer is automatically nulled", "Undefined behavior"),
    ("C++", "medium", "What is function overloading in C++?",
     "Defining multiple functions with the same name but different parameters", "Calling a function recursively", "Overriding a base class function", "Declaring a function as virtual", "Defining multiple functions with the same name but different parameters"),
    ("C++", "medium", "What is the purpose of a constructor in C++?",
     "To destroy an object", "To initialize an object when it is created", "To copy a class", "To allocate static memory only", "To initialize an object when it is created"),
    ("C++", "medium", "Which keyword enables runtime polymorphism in C++?",
     "static", "virtual", "inline", "friend", "virtual"),
    ("C++", "medium", "What does 'this' pointer refer to in a C++ class?",
     "The base class", "The current object instance", "A static member", "The first member function", "The current object instance"),
    ("C++", "medium", "Which of these correctly describes a reference variable in C++?",
     "It is a new variable with its own memory", "It is an alias for an already existing variable", "It can be reassigned to refer to a different variable", "It must always be a pointer", "It is an alias for an already existing variable"),
    ("C++", "medium", "What is operator overloading used for?",
     "Redefining the meaning of operators for user-defined types", "Creating new operators", "Improving loop performance", "Only for arithmetic on integers", "Redefining the meaning of operators for user-defined types"),
    ("C++", "medium", "Which access specifier allows access only within the class and its derived classes?",
     "public", "private", "protected", "internal", "protected"),
    ("C++", "medium", "What is the purpose of a destructor in C++?",
     "To initialize an object", "To clean up resources when an object goes out of scope", "To copy an object", "To overload an operator", "To clean up resources when an object goes out of scope"),
    ("C++", "medium", "Which STL container stores elements in key-sorted order by default?",
     "vector", "map", "list", "stack", "map"),
    ("C++", "medium", "What does the 'friend' keyword allow in C++?",
     "A function/class outside a class to access its private members", "A class to inherit from itself", "A variable to be constant", "A function to be virtual", "A function/class outside a class to access its private members"),
    ("C++", "medium", "Which of these best describes function templates in C++?",
     "Functions that work with a single fixed data type", "Functions that can operate on generic/parameterized data types", "Functions that cannot return a value", "Functions that are always inline", "Functions that can operate on generic/parameterized data types"),
    ("C++", "medium", "What is the output of cout << 5/2; in C++?",
     "2.5", "2", "3", "Error", "2"),
    ("C++", "medium", "Which of these is used to catch exceptions in C++?",
     "except", "catch", "rescue", "handle", "catch"),
    ("C++", "medium", "What is the scope resolution operator in C++?",
     "->", "::", ".", "&", "::"),
    ("C++", "hard", "What is the time complexity of a single nested loop over n items each?",
     "O(n)", "O(log n)", "O(n^2)", "O(1)", "O(n^2)"),
    ("C++", "hard", "Which of these best describes a pure virtual function?",
     "A function with a default body that can be optional", "A function declared with '= 0' that makes the class abstract", "A static function that cannot be overridden", "A function that only works with templates", "A function declared with '= 0' that makes the class abstract"),
    ("C++", "hard", "What is the primary purpose of RAII (Resource Acquisition Is Initialization) in C++?",
     "To speed up compilation", "To tie resource lifetime to object lifetime for automatic cleanup", "To enable multiple inheritance", "To replace all pointers with references", "To tie resource lifetime to object lifetime for automatic cleanup"),
    ("C++", "hard", "What does a memory leak in C++ typically result from?",
     "Using too many stack variables", "Allocating memory with new and never releasing it with delete", "Using references instead of pointers", "Declaring too many classes", "Allocating memory with new and never releasing it with delete"),
    ("C++", "hard", "Which smart pointer in modern C++ (C++11+) does NOT allow shared ownership?",
     "shared_ptr", "unique_ptr", "weak_ptr (it observes but doesn't own)", "auto_ptr", "unique_ptr"),
    ("C++", "hard", "What is the diamond problem in C++ multiple inheritance?",
     "A syntax error with templates", "Ambiguity when a class inherits from two classes that share a common base class", "An issue with operator overloading", "A memory alignment issue", "Ambiguity when a class inherits from two classes that share a common base class"),
    ("C++", "hard", "What does 'const correctness' refer to in C++?",
     "Using const only for global variables", "Using const to prevent unintended modification of data through pointers/references/methods", "A compiler optimization flag", "A naming convention for classes", "Using const to prevent unintended modification of data through pointers/references/methods"),
    ("C++", "hard", "What is the main difference between stack and heap memory allocation in C++?",
     "Stack is manually managed with new/delete, heap is automatic", "Stack is automatically managed and fast; heap is manually managed via new/delete and slower", "They are identical in C++", "Heap memory is always faster to access", "Stack is automatically managed and fast; heap is manually managed via new/delete and slower"),
    ("C++", "hard", "Which of the following best explains move semantics introduced in C++11?",
     "Copying an object's resources every time", "Transferring resources from a temporary object instead of copying them", "A way to move files on disk", "A garbage collection mechanism", "Transferring resources from a temporary object instead of copying them"),
    ("C++", "hard", "What does the 'mutable' keyword allow inside a const member function?",
     "Nothing, it is a syntax error", "Modification of the specific member variable marked mutable", "Modification of any member variable", "Deletion of the object", "Modification of the specific member variable marked mutable"),
    ("C++", "hard", "Which STL container provides O(1) average time complexity for insertion and lookup by key?",
     "map", "set", "unordered_map", "list", "unordered_map"),
    ("C++", "hard", "What is name mangling in C++?",
     "A compiler technique encoding function signatures into unique symbol names to support overloading", "A runtime error type", "A memory corruption bug", "A template instantiation failure", "A compiler technique encoding function signatures into unique symbol names to support overloading"),

    # =====================================================
    # DBMS - 48 questions
    # =====================================================
    ("DBMS", "easy", "Which SQL keyword retrieves data from a table?",
     "GET", "SELECT", "FETCH", "SHOW", "SELECT"),
    ("DBMS", "easy", "Which SQL clause is used to filter rows?",
     "WHERE", "HAVING", "GROUP BY", "ORDER BY", "WHERE"),
    ("DBMS", "easy", "What does DBMS stand for?",
     "Database Management System", "Data Backup Management Software", "Database Modeling Service", "Data Block Management System", "Database Management System"),
    ("DBMS", "easy", "Which SQL statement is used to add new data to a table?",
     "ADD", "INSERT INTO", "CREATE", "UPDATE", "INSERT INTO"),
    ("DBMS", "easy", "Which key uniquely identifies a record in a table?",
     "Foreign key", "Primary key", "Candidate key", "Composite key", "Primary key"),
    ("DBMS", "easy", "Which SQL command is used to remove a table completely?",
     "DELETE", "DROP", "REMOVE", "TRUNCATE only", "DROP"),
    ("DBMS", "easy", "Which SQL clause sorts the result set?",
     "SORT BY", "ORDER BY", "GROUP BY", "ARRANGE BY", "ORDER BY"),
    ("DBMS", "easy", "What is a foreign key used for?",
     "To uniquely identify a row in its own table", "To link a record to a primary key in another table", "To encrypt data", "To index a column", "To link a record to a primary key in another table"),
    ("DBMS", "easy", "Which SQL statement modifies existing records?",
     "MODIFY", "UPDATE", "ALTER", "CHANGE", "UPDATE"),
    ("DBMS", "easy", "Which of these is a Database Management System?",
     "MySQL", "HTML", "Photoshop", "Excel formulas", "MySQL"),
    ("DBMS", "easy", "What does SQL stand for?",
     "Structured Query Language", "Simple Query Language", "Sequential Query Logic", "Standard Query List", "Structured Query Language"),
    ("DBMS", "easy", "Which command permanently removes all rows from a table but keeps its structure?",
     "DELETE", "DROP", "TRUNCATE", "REMOVE", "TRUNCATE"),
    ("DBMS", "easy", "Which of these is used to rename a column or table in SQL?",
     "RENAME/AS", "MODIFY", "CHANGE", "SET", "RENAME/AS"),
    ("DBMS", "easy", "Which SQL keyword is used to remove duplicate rows from a result?",
     "UNIQUE", "DISTINCT", "ONLY", "SINGLE", "DISTINCT"),
    ("DBMS", "medium", "Which normal form removes partial dependency?",
     "1NF", "2NF", "3NF", "BCNF", "2NF"),
    ("DBMS", "medium", "Which normal form removes transitive dependency?",
     "1NF", "2NF", "3NF", "0NF", "3NF"),
    ("DBMS", "medium", "Which join returns unmatched rows from both tables?",
     "INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN", "FULL OUTER JOIN"),
    ("DBMS", "medium", "Which SQL clause is used to filter grouped results?",
     "WHERE", "HAVING", "FILTER", "GROUP", "HAVING"),
    ("DBMS", "medium", "What is the purpose of a transaction in a DBMS?",
     "To speed up queries", "To group operations so they all succeed or all fail together", "To create indexes automatically", "To back up the database", "To group operations so they all succeed or all fail together"),
    ("DBMS", "medium", "What does the ACID property 'Atomicity' guarantee?",
     "Transactions are visible to other users immediately", "A transaction is all-or-nothing", "Data is always encrypted", "Queries run in parallel", "A transaction is all-or-nothing"),
    ("DBMS", "medium", "Which type of join returns only the matching rows from both tables?",
     "LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "CROSS JOIN", "INNER JOIN"),
    ("DBMS", "medium", "What is a candidate key?",
     "Any key that can uniquely identify a row and could be chosen as the primary key", "A key with duplicate values allowed", "A foreign key from another table", "An index on a non-unique column", "Any key that can uniquely identify a row and could be chosen as the primary key"),
    ("DBMS", "medium", "What does the SQL GROUP BY clause do?",
     "Sorts the result set", "Groups rows sharing a value so aggregate functions can be applied per group", "Filters individual rows", "Joins two tables", "Groups rows sharing a value so aggregate functions can be applied per group"),
    ("DBMS", "medium", "What is denormalization used for?",
     "Removing all redundancy from a database", "Intentionally introducing redundancy to improve read performance", "Encrypting sensitive columns", "Creating foreign keys", "Intentionally introducing redundancy to improve read performance"),
    ("DBMS", "medium", "Which SQL aggregate function returns the number of rows?",
     "SUM()", "COUNT()", "TOTAL()", "ADD()", "COUNT()"),
    ("DBMS", "medium", "What is an index in a database used for?",
     "To enforce foreign key constraints", "To speed up data retrieval at the cost of extra storage/write overhead", "To encrypt table data", "To normalize a table", "To speed up data retrieval at the cost of extra storage/write overhead"),
    ("DBMS", "medium", "What does a composite key consist of?",
     "A single auto-incrementing column", "Two or more columns combined to uniquely identify a row", "A foreign key only", "An encrypted column", "Two or more columns combined to uniquely identify a row"),
    ("DBMS", "medium", "Which SQL command is used to give access privileges to a user?",
     "ALLOW", "GRANT", "PERMIT", "ACCESS", "GRANT"),
    ("DBMS", "medium", "What is the purpose of a view in SQL?",
     "To physically store a duplicate copy of a table", "To present a virtual table based on the result of a stored query", "To delete rows automatically", "To create a backup", "To present a virtual table based on the result of a stored query"),
    ("DBMS", "medium", "What does referential integrity ensure?",
     "All columns have unique values", "A foreign key value always matches an existing primary key value (or is null)", "Tables are always normalized to 3NF", "Queries execute faster", "A foreign key value always matches an existing primary key value (or is null)"),
    ("DBMS", "hard", "Which of these best describes the Isolation property in ACID?",
     "Transactions are executed one after another with no concurrency", "Concurrent transactions produce results as if they were executed serially", "Data is never lost after a crash", "All operations in a transaction succeed together", "Concurrent transactions produce results as if they were executed serially"),
    ("DBMS", "hard", "What is a deadlock in a DBMS?",
     "A query that never returns results", "A situation where two or more transactions wait indefinitely for each other's locks", "A corrupted index", "A failed backup operation", "A situation where two or more transactions wait indefinitely for each other's locks"),
    ("DBMS", "hard", "Which normal form deals with multi-valued dependencies?",
     "2NF", "3NF", "BCNF", "4NF", "4NF"),
    ("DBMS", "hard", "What is the primary difference between BCNF and 3NF?",
     "BCNF is less strict than 3NF", "BCNF requires every determinant to be a candidate key, which is stricter than 3NF", "They are identical", "3NF only applies to single-column tables", "BCNF requires every determinant to be a candidate key, which is stricter than 3NF"),
    ("DBMS", "hard", "What does two-phase locking (2PL) guarantee in concurrency control?",
     "Faster query execution", "Serializability of concurrent transactions", "Automatic deadlock prevention", "Reduced storage usage", "Serializability of concurrent transactions"),
    ("DBMS", "hard", "What is a clustered index?",
     "An index stored separately that points to row locations", "An index that determines the physical storage order of table data", "An index only usable on primary keys", "A temporary in-memory index", "An index that determines the physical storage order of table data"),
    ("DBMS", "hard", "What does the CAP theorem state about distributed databases?",
     "A system can guarantee Consistency, Availability, and Partition tolerance all at once", "A distributed system can only guarantee two of Consistency, Availability, and Partition tolerance at the same time", "Partition tolerance is optional in distributed systems", "CAP only applies to relational databases", "A distributed system can only guarantee two of Consistency, Availability, and Partition tolerance at the same time"),
    ("DBMS", "hard", "What is the purpose of a write-ahead log (WAL) in database recovery?",
     "To log user login attempts", "To record changes before they are applied, enabling recovery after a crash", "To speed up SELECT queries", "To enforce foreign key constraints", "To record changes before they are applied, enabling recovery after a crash"),
    ("DBMS", "hard", "Which isolation level allows a transaction to read uncommitted changes from another transaction?",
     "Serializable", "Repeatable Read", "Read Committed", "Read Uncommitted", "Read Uncommitted"),
    ("DBMS", "hard", "What is a phantom read in transaction isolation?",
     "Reading a deleted row", "A transaction re-runs a query and finds new rows that match the condition inserted by another transaction", "A read that returns corrupted data", "A read that times out", "A transaction re-runs a query and finds new rows that match the condition inserted by another transaction"),

    # =====================================================
    # WEB DEVELOPMENT - 48 questions
    # =====================================================
    ("Web Development", "easy", "What does HTML stand for?",
     "Hyper Trainer Marking Language", "HyperText Markup Language", "Hyper Text Making Language", "High Text Markup Language", "HyperText Markup Language"),
    ("Web Development", "easy", "Which tag is used to create a hyperlink in HTML?",
     "<link>", "<a>", "<href>", "<url>", "<a>"),
    ("Web Development", "easy", "Which CSS property changes the text color?",
     "font-color", "text-color", "color", "fg-color", "color"),
    ("Web Development", "easy", "Which HTML tag is used to define an unordered list?",
     "<ol>", "<ul>", "<list>", "<li>", "<ul>"),
    ("Web Development", "easy", "Which language is primarily used to style web pages?",
     "HTML", "CSS", "JSON", "XML", "CSS"),
    ("Web Development", "easy", "Which tag is used to insert an image in HTML?",
     "<image>", "<img>", "<pic>", "<src>", "<img>"),
    ("Web Development", "easy", "Which CSS property controls the space between flex items?",
     "margin", "gap", "padding", "spacing", "gap"),
    ("Web Development", "easy", "What does CSS stand for?",
     "Creative Style Sheets", "Cascading Style Sheets", "Computer Style Sheets", "Colorful Style Sheets", "Cascading Style Sheets"),
    ("Web Development", "easy", "Which attribute specifies an alternate text for an image?",
     "title", "alt", "src", "caption", "alt"),
    ("Web Development", "easy", "Which HTML tag is used to define the largest heading?",
     "<h6>", "<heading>", "<h1>", "<head>", "<h1>"),
    ("Web Development", "easy", "Which symbol is used to select an element by class in CSS?",
     "#", ".", "*", "&", "."),
    ("Web Development", "easy", "Which symbol is used to select an element by ID in CSS?",
     "#", ".", "*", "@", "#"),
    ("Web Development", "easy", "Which JavaScript keyword declares a variable that can be reassigned?",
     "const", "let", "final", "static", "let"),
    ("Web Development", "easy", "Which HTML tag creates a table row?",
     "<td>", "<tr>", "<th>", "<row>", "<tr>"),
    ("Web Development", "medium", "What does the JavaScript event loop primarily manage?",
     "CSS rendering order", "Execution of async callbacks and microtasks", "DOM tree structure", "HTTP request headers", "Execution of async callbacks and microtasks"),
    ("Web Development", "medium", "Which loop is best when the number of iterations is unknown in advance?",
     "for loop", "while loop", "do-while loop", "range loop", "while loop"),
    ("Web Development", "medium", "What is the purpose of the box-sizing: border-box CSS property?",
     "Removes all borders from an element", "Includes padding and border in an element's total width/height", "Rounds the corners of a box", "Adds a shadow to a box", "Includes padding and border in an element's total width/height"),
    ("Web Development", "medium", "What does 'responsive design' primarily refer to?",
     "A website that loads faster", "A website layout that adapts to different screen sizes", "A website with animations", "A website written only in JavaScript", "A website layout that adapts to different screen sizes"),
    ("Web Development", "medium", "Which HTTP method is typically used to submit new data to a server?",
     "GET", "POST", "HEAD", "OPTIONS", "POST"),
    ("Web Development", "medium", "What is the difference between let and var in JavaScript?",
     "No difference at all", "let is block-scoped, var is function-scoped", "var is block-scoped, let is function-scoped", "let cannot hold objects", "let is block-scoped, var is function-scoped"),
    ("Web Development", "medium", "What does REST stand for in the context of web APIs?",
     "Representational State Transfer", "Remote Execution State Transfer", "Reliable State Transmission", "Representational Server Technology", "Representational State Transfer"),
    ("Web Development", "medium", "Which CSS layout model is designed for one-dimensional (row or column) layouts?",
     "Grid", "Flexbox", "Float", "Table", "Flexbox"),
    ("Web Development", "medium", "What is the DOM in web development?",
     "A database query language", "A programming interface representing the structure of an HTML document", "A CSS preprocessor", "A JavaScript testing framework", "A programming interface representing the structure of an HTML document"),
    ("Web Development", "medium", "What is the purpose of AJAX in web development?",
     "To style web pages", "To send/receive data from a server asynchronously without reloading the page", "To define the HTML document structure", "To compile JavaScript", "To send/receive data from a server asynchronously without reloading the page"),
    ("Web Development", "medium", "What does CORS stand for?",
     "Cross-Origin Resource Sharing", "Common Object Request Service", "Client-Origin Response System", "Cross-Object Rendering Style", "Cross-Origin Resource Sharing"),
    ("Web Development", "medium", "Which of these correctly describes a JavaScript Promise?",
     "A synchronous function call", "An object representing the eventual completion or failure of an async operation", "A CSS animation type", "A type of HTML form", "An object representing the eventual completion or failure of an async operation"),
    ("Web Development", "medium", "What is the purpose of media queries in CSS?",
     "To query a database from CSS", "To apply different styles based on device characteristics like screen width", "To load images faster", "To define animations", "To apply different styles based on device characteristics like screen width"),
    ("Web Development", "medium", "Which HTTP status code indicates a successful request?",
     "404", "500", "200", "301", "200"),
    ("Web Development", "medium", "What does JSON stand for?",
     "JavaScript Object Notation", "Java Standard Object Network", "JavaScript Ordered Nodes", "Joint Style Object Notation", "JavaScript Object Notation"),
    ("Web Development", "medium", "What is the purpose of localStorage in web browsers?",
     "To store data on the server", "To store key-value data in the browser that persists after the page is closed", "To cache CSS files only", "To manage HTTP cookies exclusively", "To store key-value data in the browser that persists after the page is closed"),
    ("Web Development", "hard", "What is the performance concern typically discussed with deeply nested DOM manipulation loops?",
     "It has no performance impact", "Repeated reflows/repaints can make it behave like O(n^2) in practice for large DOMs", "It always runs in O(1)", "It only affects CSS, not JavaScript", "Repeated reflows/repaints can make it behave like O(n^2) in practice for large DOMs"),
    ("Web Development", "hard", "What construct does JavaScript rely on to handle errors inside async/await code?",
     "try/catch blocks around await expressions", "The else keyword directly", "CSS pseudo-classes", "HTML form validation", "try/catch blocks around await expressions"),
    ("Web Development", "hard", "What is the primary purpose of a Content Delivery Network (CDN)?",
     "To compile JavaScript into machine code", "To serve static assets from servers geographically closer to users for speed", "To replace a database", "To encrypt HTML content", "To serve static assets from servers geographically closer to users for speed"),
    ("Web Development", "hard", "What does the term 'hydration' mean in modern JavaScript frameworks (e.g. Next.js, Nuxt)?",
     "Compressing images automatically", "Attaching client-side JavaScript behavior to server-rendered static HTML", "Minifying CSS files", "Caching API responses", "Attaching client-side JavaScript behavior to server-rendered static HTML"),
    ("Web Development", "hard", "What is a race condition in the context of asynchronous JavaScript?",
     "A CSS animation timing bug", "An outcome depending unpredictably on the relative timing of async operations", "A syntax error in Promises", "A type of memory leak only", "An outcome depending unpredictably on the relative timing of async operations"),
    ("Web Development", "hard", "What is the main security risk that CSRF (Cross-Site Request Forgery) protection defends against?",
     "SQL injection", "A malicious site tricking a logged-in user's browser into making unwanted authenticated requests", "Brute-force password attacks", "DNS spoofing", "A malicious site tricking a logged-in user's browser into making unwanted authenticated requests"),
    ("Web Development", "hard", "What does 'critical rendering path' refer to in browser performance?",
     "The sequence of steps the browser takes to convert HTML/CSS/JS into pixels on screen", "The order JavaScript files are downloaded", "The database query execution plan", "The HTTP request retry logic", "The sequence of steps the browser takes to convert HTML/CSS/JS into pixels on screen"),
    ("Web Development", "hard", "What is the primary difference between authentication and authorization?",
     "They are the same concept", "Authentication verifies WHO you are; authorization determines WHAT you're allowed to do", "Authorization always happens before authentication", "Authentication only applies to APIs", "Authentication verifies WHO you are; authorization determines WHAT you're allowed to do"),
    ("Web Development", "hard", "What does 'debouncing' a function typically achieve in frontend performance?",
     "Running a function immediately every time it's called", "Delaying a function's execution until after a pause in repeated calls (e.g. search-as-you-type)", "Caching a function's return value forever", "Running a function on a separate thread", "Delaying a function's execution until after a pause in repeated calls (e.g. search-as-you-type)"),

    # =====================================================
    # MACHINE LEARNING - 48 questions
    # =====================================================
    ("Machine Learning", "easy", "Which of these is a supervised learning task?",
     "Clustering", "Dimensionality reduction", "Classification", "Anomaly detection without labels", "Classification"),
    ("Machine Learning", "easy", "What does the term 'label' refer to in supervised learning?",
     "An input feature", "The known correct output for a training example", "A type of algorithm", "A hyperparameter", "The known correct output for a training example"),
    ("Machine Learning", "easy", "Which of these is an example of unsupervised learning?",
     "Linear regression", "K-Means clustering", "Logistic regression", "Decision tree classification", "K-Means clustering"),
    ("Machine Learning", "easy", "What is a 'feature' in machine learning?",
     "The final prediction", "An individual measurable input variable used for prediction", "A type of neural network layer", "An evaluation metric", "An individual measurable input variable used for prediction"),
    ("Machine Learning", "easy", "What does 'training data' refer to?",
     "Data used to evaluate the final model only", "Data used to fit/teach the model's parameters", "Randomly generated noise", "Data that is never used", "Data used to fit/teach the model's parameters"),
    ("Machine Learning", "easy", "Which of these best describes regression in machine learning?",
     "Predicting a discrete category", "Predicting a continuous numeric value", "Grouping unlabeled data", "Reducing the number of features", "Predicting a continuous numeric value"),
    ("Machine Learning", "easy", "What does 'overfitting' mean?",
     "The model performs poorly on both training and test data", "The model learns the training data too well, including noise, and generalizes poorly", "The model is too simple to learn patterns", "The model trains too quickly", "The model learns the training data too well, including noise, and generalizes poorly"),
    ("Machine Learning", "easy", "Which of these is a commonly used programming library for machine learning in Python?",
     "scikit-learn", "Bootstrap", "jQuery", "Django", "scikit-learn"),
    ("Machine Learning", "easy", "What is the purpose of splitting data into training and test sets?",
     "To make the dataset smaller for storage", "To evaluate how well the model generalizes to unseen data", "To speed up data collection", "To remove duplicate rows", "To evaluate how well the model generalizes to unseen data"),
    ("Machine Learning", "easy", "Which of these is NOT typically a machine learning task?",
     "Image classification", "Spam detection", "Sorting a static list of numbers", "Predicting house prices", "Sorting a static list of numbers"),
    ("Machine Learning", "easy", "What does 'underfitting' mean?",
     "The model is too complex", "The model is too simple to capture the underlying pattern in the data", "The model perfectly memorizes training data", "The model has too many features", "The model is too simple to capture the underlying pattern in the data"),
    ("Machine Learning", "easy", "Which of these is an example of a classification label?",
     "23.5", "'Spam' or 'Not Spam'", "A timestamp", "A row index", "'Spam' or 'Not Spam'"),
    ("Machine Learning", "easy", "What is a dataset in machine learning?",
     "A single data point", "A collection of data samples used for training/testing", "A type of algorithm", "A visualization tool", "A collection of data samples used for training/testing"),
    ("Machine Learning", "medium", "Which metric is most sensitive to class imbalance?",
     "Accuracy", "F1 Score", "Mean Squared Error", "R-squared", "Accuracy"),
    ("Machine Learning", "medium", "What does the 'learning rate' control in gradient descent?",
     "The number of training examples used", "The step size taken toward minimizing the loss function", "The number of features selected", "The final accuracy directly", "The step size taken toward minimizing the loss function"),
    ("Machine Learning", "medium", "What is the purpose of cross-validation?",
     "To increase the size of the dataset", "To get a more reliable estimate of model performance by testing on multiple data splits", "To remove outliers automatically", "To visualize high-dimensional data", "To get a more reliable estimate of model performance by testing on multiple data splits"),
    ("Machine Learning", "medium", "What does a confusion matrix summarize?",
     "The runtime of a model", "The counts of true/false positives and negatives for a classifier", "The number of features in a dataset", "The learning rate schedule", "The counts of true/false positives and negatives for a classifier"),
    ("Machine Learning", "medium", "What is regularization used for in machine learning?",
     "To speed up data loading", "To penalize model complexity and reduce overfitting", "To increase the number of features", "To normalize the output labels", "To penalize model complexity and reduce overfitting"),
    ("Machine Learning", "medium", "What does 'feature scaling' (e.g. normalization) help with?",
     "Removing all features from a dataset", "Bringing features to a similar scale so no single feature dominates due to its range", "Generating new labels", "Encrypting sensitive data", "Bringing features to a similar scale so no single feature dominates due to its range"),
    ("Machine Learning", "medium", "Which algorithm is commonly used for binary classification and outputs probabilities?",
     "Linear regression", "Logistic regression", "K-Means", "PCA", "Logistic regression"),
    ("Machine Learning", "medium", "What is the purpose of a validation set?",
     "To train the final model", "To tune hyperparameters and select models without touching the test set", "To replace the training set", "To visualize raw data only", "To tune hyperparameters and select models without touching the test set"),
    ("Machine Learning", "medium", "What does 'precision' measure in classification?",
     "Of all actual positives, how many were correctly predicted", "Of all predicted positives, how many were actually positive", "Overall percentage of correct predictions", "The speed of the model", "Of all predicted positives, how many were actually positive"),
    ("Machine Learning", "medium", "What does 'recall' measure in classification?",
     "Of all predicted positives, how many were actually positive", "Of all actual positives, how many were correctly identified", "The model's training time", "The number of features used", "Of all actual positives, how many were correctly identified"),
    ("Machine Learning", "medium", "What is the purpose of a decision tree's splitting criterion (e.g. Gini impurity)?",
     "To decide which feature/value best separates the data at each node", "To determine the learning rate", "To normalize input features", "To count the number of leaves", "To decide which feature/value best separates the data at each node"),
    ("Machine Learning", "medium", "What does 'one-hot encoding' do to a categorical feature?",
     "Converts it to a single numeric average", "Converts it into multiple binary columns, one per category", "Removes it from the dataset", "Compresses it using PCA", "Converts it into multiple binary columns, one per category"),
    ("Machine Learning", "medium", "What is ensemble learning?",
     "Using only one very large model", "Combining predictions from multiple models to improve overall performance", "Training a model without any data", "A method to visualize decision boundaries", "Combining predictions from multiple models to improve overall performance"),
    ("Machine Learning", "medium", "What does the bias-variance tradeoff describe?",
     "The balance between model simplicity (bias) and sensitivity to training data (variance)", "The tradeoff between CPU and GPU usage", "The choice between supervised and unsupervised learning", "The tradeoff between accuracy and training data size only", "The balance between model simplicity (bias) and sensitivity to training data (variance)"),
    ("Machine Learning", "hard", "What is the primary purpose of Principal Component Analysis (PCA)?",
     "To classify labeled data", "To reduce dimensionality while preserving as much variance as possible", "To perform text tokenization", "To tune hyperparameters automatically", "To reduce dimensionality while preserving as much variance as possible"),
    ("Machine Learning", "hard", "What does the vanishing gradient problem refer to in deep neural networks?",
     "Gradients becoming excessively large during backpropagation", "Gradients becoming extremely small in earlier layers, slowing or stopping learning", "The loss function disappearing entirely", "A hardware memory error", "Gradients becoming extremely small in earlier layers, slowing or stopping learning"),
    ("Machine Learning", "hard", "What is the role of an activation function in a neural network?",
     "To normalize the dataset before training", "To introduce non-linearity so the network can learn complex patterns", "To split data into train/test sets", "To calculate the learning rate", "To introduce non-linearity so the network can learn complex patterns"),
    ("Machine Learning", "hard", "What does 'dropout' do when used as a regularization technique in neural networks?",
     "Permanently removes a percentage of the training data", "Randomly deactivates a fraction of neurons during training to reduce overfitting", "Increases the learning rate over time", "Adds more layers to the network", "Randomly deactivates a fraction of neurons during training to reduce overfitting"),
    ("Machine Learning", "hard", "What is the kernel trick used for in Support Vector Machines?",
     "To speed up data loading", "To implicitly map data into a higher-dimensional space to find a linear separator without computing the transformation explicitly", "To reduce the number of support vectors", "To normalize the output labels", "To implicitly map data into a higher-dimensional space to find a linear separator without computing the transformation explicitly"),
    ("Machine Learning", "hard", "What does 'stochastic' mean in Stochastic Gradient Descent (SGD)?",
     "The gradient is computed using the entire dataset every step", "The gradient is estimated using a randomly sampled subset (or single example) at each step", "The learning rate is fixed forever", "The algorithm never converges", "The gradient is estimated using a randomly sampled subset (or single example) at each step"),
    ("Machine Learning", "hard", "What is the exploding gradient problem?",
     "Gradients shrink to near zero during training", "Gradients grow uncontrollably large during backpropagation, destabilizing training", "The model's accuracy explodes to 100% instantly", "A dataset that grows too large to fit in memory", "Gradients grow uncontrollably large during backpropagation, destabilizing training"),
    ("Machine Learning", "hard", "What does the term 'hyperparameter' mean, as opposed to a 'parameter'?",
     "A value learned automatically from data during training", "A configuration set before training (e.g. learning rate, number of layers) that is not learned from data", "A synonym for a feature", "A type of loss function", "A configuration set before training (e.g. learning rate, number of layers) that is not learned from data"),
    ("Machine Learning", "hard", "What is transfer learning?",
     "Training a brand-new model from scratch every time", "Reusing a model trained on one task as a starting point for a related task", "Moving a trained model to a different programming language", "A method for cleaning missing data", "Reusing a model trained on one task as a starting point for a related task"),
    ("Machine Learning", "hard", "What is the primary difference between bagging and boosting in ensemble methods?",
     "They are exactly the same technique", "Bagging trains models independently in parallel on random subsets; boosting trains models sequentially, each correcting the previous one's errors", "Boosting only works with neural networks", "Bagging always performs worse than a single model", "Bagging trains models independently in parallel on random subsets; boosting trains models sequentially, each correcting the previous one's errors"),

    # =====================================================
    # SUPPLEMENTARY TOP-UP BATCH
    # Brings Java, C++, DBMS, Web Development and Machine Learning
    # up to at least 50 questions each (Python already has 50).
    # =====================================================
    ("Java", "easy", "Which of these is a valid Java comment for multiple lines?",
     "// comment", "/* comment */", "# comment", "<!-- comment -->", "/* comment */"),
    ("Java", "medium", "Which keyword is used to import a package in Java?",
     "include", "import", "using", "require", "import"),
    ("Java", "hard", "What is the purpose of the 'Comparable' interface in Java?",
     "To compare object memory addresses", "To define a natural ordering for objects of a class via compareTo()", "To make a class immutable", "To enable serialization", "To define a natural ordering for objects of a class via compareTo()"),

    ("C++", "easy", "Which of these is the correct way to declare a function prototype in C++?",
     "int add(int, int);", "function add(int, int);", "def add(int, int):", "int add(int, int) {}", "int add(int, int);"),
    ("C++", "easy", "Which operator is used to get the address of a variable in C++?",
     "*", "&", "#", "@", "&"),
    ("C++", "easy", "Which of these correctly declares an array of 5 integers?",
     "int arr[5];", "int arr(5);", "array int[5];", "int[5] arr;", "int arr[5];"),
    ("C++", "medium", "What is the purpose of the 'inline' keyword in C++?",
     "To suggest the compiler replace a function call with the function body to reduce call overhead", "To make a function private", "To make a variable global", "To force dynamic memory allocation", "To suggest the compiler replace a function call with the function body to reduce call overhead"),
    ("C++", "medium", "Which STL container provides LIFO (Last In First Out) behavior?",
     "queue", "stack", "vector", "map", "stack"),
    ("C++", "medium", "Which STL container provides FIFO (First In First Out) behavior?",
     "stack", "queue", "set", "map", "queue"),
    ("C++", "hard", "What does the 'explicit' keyword prevent in a C++ constructor?",
     "Multiple constructors in one class", "Implicit type conversions using that constructor", "Inheritance from the class", "Use of default arguments", "Implicit type conversions using that constructor"),
    ("C++", "hard", "What is a lambda expression in modern C++ (C++11+)?",
     "A named function only", "An anonymous inline function that can capture variables from its enclosing scope", "A type of pointer", "A preprocessor macro", "An anonymous inline function that can capture variables from its enclosing scope"),
    ("C++", "hard", "What does 'undefined behavior' mean in C++?",
     "The compiler always throws a clear error", "Code whose behavior the C++ standard does not define, so results are unpredictable", "A warning that can be safely ignored", "A runtime exception that is always caught", "Code whose behavior the C++ standard does not define, so results are unpredictable"),

    ("DBMS", "easy", "Which SQL command creates a new table?",
     "MAKE TABLE", "CREATE TABLE", "NEW TABLE", "ADD TABLE", "CREATE TABLE"),
    ("DBMS", "easy", "What does a NULL value in a database column represent?",
     "The number zero", "An empty string", "The absence of a value / unknown value", "A negative number", "The absence of a value / unknown value"),
    ("DBMS", "easy", "Which SQL keyword combines rows from two or more tables based on a related column?",
     "MERGE", "JOIN", "LINK", "COMBINE", "JOIN"),
    ("DBMS", "medium", "What does the SQL 'BETWEEN' operator do?",
     "Selects values within a given range (inclusive)", "Selects values outside a range", "Compares two columns for equality", "Sorts values numerically", "Selects values within a given range (inclusive)"),
    ("DBMS", "medium", "Which of these best describes a self-join?",
     "Joining a table to itself using aliases", "A join that always fails", "A join without any condition", "A join between two different databases", "Joining a table to itself using aliases"),
    ("DBMS", "medium", "What is the purpose of the SQL 'ALTER TABLE' statement?",
     "To delete a table", "To modify an existing table's structure (add/drop/modify columns)", "To insert new rows", "To create a backup", "To modify an existing table's structure (add/drop/modify columns)"),
    ("DBMS", "medium", "What does 'entity-relationship (ER) modeling' primarily describe?",
     "SQL query optimization", "A conceptual design showing entities, attributes, and relationships in a database", "A backup and recovery strategy", "A type of index", "A conceptual design showing entities, attributes, and relationships in a database"),
    ("DBMS", "hard", "What is the main advantage of using a stored procedure?",
     "It replaces the need for indexes", "Precompiled reusable SQL logic executed on the server, reducing network round-trips", "It automatically normalizes tables", "It removes the need for primary keys", "Precompiled reusable SQL logic executed on the server, reducing network round-trips"),
    ("DBMS", "hard", "What does 'sharding' refer to in database architecture?",
     "Encrypting a database", "Horizontally partitioning data across multiple database instances/servers", "Creating a full backup", "Removing duplicate rows", "Horizontally partitioning data across multiple database instances/servers"),
    ("DBMS", "hard", "Which of these best describes optimistic concurrency control?",
     "Locks are held for the entire transaction duration", "Transactions proceed without locking and are validated for conflicts before committing", "It disables concurrency entirely", "It only works with NoSQL databases", "Transactions proceed without locking and are validated for conflicts before committing"),

    ("Web Development", "easy", "Which HTML tag is used to define the document's title shown in the browser tab?",
     "<header>", "<title>", "<caption>", "<name>", "<title>"),
    ("Web Development", "easy", "Which CSS property is used to change the background color of an element?",
     "bg-color", "background-color", "color-background", "bgcolor", "background-color"),
    ("Web Development", "easy", "Which HTML5 tag is used to define navigation links?",
     "<navigation>", "<nav>", "<links>", "<menu>", "<nav>"),
    ("Web Development", "medium", "What is the purpose of the 'viewport' meta tag in responsive web design?",
     "To set the page title", "To control the page's dimensions and scaling on different devices", "To load external scripts", "To define the page's character encoding", "To control the page's dimensions and scaling on different devices"),
    ("Web Development", "medium", "What does the 'z-index' CSS property control?",
     "Horizontal position of an element", "The stack order of overlapping positioned elements", "Font size scaling", "The number of grid columns", "The stack order of overlapping positioned elements"),
    ("Web Development", "medium", "Which of these correctly describes CSS specificity?",
     "All selectors have equal weight", "A set of rules determining which CSS rule applies when multiple rules target the same element", "Only inline styles matter", "Specificity only applies to JavaScript", "A set of rules determining which CSS rule applies when multiple rules target the same element"),
    ("Web Development", "medium", "What is the purpose of the 'fetch()' API in JavaScript?",
     "To style DOM elements", "To make HTTP requests and handle responses using Promises", "To declare variables", "To define CSS animations", "To make HTTP requests and handle responses using Promises"),
    ("Web Development", "hard", "What does 'tree shaking' mean in modern JavaScript bundlers?",
     "Randomly removing files from a project", "Eliminating unused code from the final bundle to reduce its size", "Sorting the DOM tree alphabetically", "A CSS animation technique", "Eliminating unused code from the final bundle to reduce its size"),
    ("Web Development", "hard", "What is the main purpose of HTTPS over HTTP?",
     "Faster page loading only", "Encrypting data in transit between client and server for security", "Better SEO ranking only", "Reducing server storage costs", "Encrypting data in transit between client and server for security"),
    ("Web Development", "hard", "What does 'progressive enhancement' mean as a web development strategy?",
     "Building a site that only works on the newest browsers", "Building a basic functional experience first, then layering on advanced features for capable browsers", "Adding animations to every element", "Using only server-side rendering", "Building a basic functional experience first, then layering on advanced features for capable browsers"),

    ("Machine Learning", "easy", "Which of these best describes a 'model' in machine learning?",
     "The raw dataset itself", "A mathematical representation learned from data used to make predictions", "A visualization chart", "A type of database", "A mathematical representation learned from data used to make predictions"),
    ("Machine Learning", "easy", "What is the goal of a loss function in machine learning?",
     "To measure how far the model's predictions are from the actual values", "To store the training data", "To visualize the dataset", "To split data into batches", "To measure how far the model's predictions are from the actual values"),
    ("Machine Learning", "easy", "Which of these is an example of a regression problem?",
     "Predicting whether an email is spam or not", "Predicting the price of a house", "Classifying an image as cat or dog", "Detecting a fraudulent transaction (yes/no)", "Predicting the price of a house"),
    ("Machine Learning", "medium", "What does 'k' represent in the K-Nearest Neighbors (KNN) algorithm?",
     "The number of features used", "The number of nearest data points considered when making a prediction", "The number of clusters", "The learning rate", "The number of nearest data points considered when making a prediction"),
    ("Machine Learning", "medium", "What is the purpose of the softmax function, commonly used in the output layer of a classifier?",
     "To normalize pixel values", "To convert raw scores into a probability distribution over multiple classes", "To reduce the number of layers", "To compute the loss directly", "To convert raw scores into a probability distribution over multiple classes"),
    ("Machine Learning", "medium", "What does 'imbalanced dataset' mean in classification?",
     "A dataset with missing values", "A dataset where one class has significantly more examples than another", "A dataset that is too large to process", "A dataset with only numeric features", "A dataset where one class has significantly more examples than another"),
    ("Machine Learning", "medium", "What is the main idea behind Random Forest as an ensemble method?",
     "Training a single very deep decision tree", "Combining predictions from many decision trees trained on random subsets of data/features", "Using only linear models", "Manually selecting the best features", "Combining predictions from many decision trees trained on random subsets of data/features"),
    ("Machine Learning", "hard", "What does 'batch size' control during neural network training?",
     "The number of layers in the network", "The number of training examples processed before the model's weights are updated", "The learning rate value", "The number of epochs", "The number of training examples processed before the model's weights are updated"),
    ("Machine Learning", "hard", "What is the purpose of an 'epoch' in training a neural network?",
     "A single forward pass on one example", "One complete pass through the entire training dataset", "A type of activation function", "A regularization technique", "One complete pass through the entire training dataset"),
    ("Machine Learning", "hard", "What does 'early stopping' help prevent during model training?",
     "Underfitting only", "Overfitting, by halting training once validation performance stops improving", "Slow training speed", "Data leakage", "Overfitting, by halting training once validation performance stops improving"),
    ("Machine Learning", "hard", "What is the primary purpose of a confusion matrix's diagonal values?",
     "They show all misclassifications", "They show the counts of correctly predicted instances for each class", "They show the total dataset size", "They show the learning rate over time", "They show the counts of correctly predicted instances for each class"),

    ("Web Development", "easy", "Which HTTP method is typically used to retrieve data without modifying it?",
     "POST", "GET", "DELETE", "PUT", "GET"),
    ("Web Development", "medium", "What is the purpose of a CSS preprocessor like Sass or LESS?",
     "To replace HTML entirely", "To add features like variables and nesting to CSS before compiling it to plain CSS", "To compress images", "To run JavaScript on the server", "To add features like variables and nesting to CSS before compiling it to plain CSS"),

    ("Machine Learning", "easy", "What does the term 'inference' typically mean once a model is trained?",
     "Retraining the model from scratch", "Using the trained model to make predictions on new, unseen data", "Deleting the training data", "Visualizing the loss curve only", "Using the trained model to make predictions on new, unseen data"),
    ("Machine Learning", "medium", "What is data leakage in machine learning?",
     "Losing part of the dataset due to a storage error", "Information from outside the training set (e.g. test data) improperly influencing the model", "A GPU running out of memory", "A model that trains too slowly", "Information from outside the training set (e.g. test data) improperly influencing the model"),
]







